FROM python:2.7

VOLUME ["/src"]
WORKDIR "/src"
EXPOSE 8080
ENTRYPOINT ["uwsgi"]

COPY ./foobar.py /src/

RUN pip install uwsgi==2.0
CMD ["--socket", "0.0.0.0:8080", "--wsgi-file", "foobar.py", "--master", "--processes", "4", "--threads", "2"]
